Compose article
Ptt-official-app/Ptt-iOS pull request #36
Opened 2021-09-14 13:58 UTC by marcussfu

1.  Add ComposeArticleFlow and follow coordinator
2. POST /api/board/{bid}/article
3. Adjust "getBoardArticles" and "getArticle" from .legacy to .go_pttbbs

2021-09-17 00:31 UTC, denkeni requested changes

2021-10-04 21:43 UTC, marcussfu commented on Ptt/Flows/ComposeArticleFlow/Controllers/ComposeArticleViewController.swift
> +        classSelectButton.setTitleColor(UIColor(red:240/255, green:240/255, blue:247/255, alpha:1.0), for: .normal)
corrected

2021-10-04 21:45 UTC, marcussfu commented on Ptt/Flows/ComposeArticleFlow/Controllers/ComposeArticleViewController.swift
> +        contentView.backgroundColor = UIColor(named: "blackColor-23-23-23")
corrected.

2021-10-04 21:52 UTC, marcussfu commented on Ptt/Flows/BoardFlow/Controllers/BoardViewController.swift
> +        refresh()
refresh after creative compose

2021-10-13 13:58 UTC, marcussfu commented on Ptt/API/Models/Article.swift
> +//            _title.removeSubrange(range)
所以上正式環境就不會有[測試]了嗎

2021-10-14 04:26 UTC, denkeni commented on Ptt/API/Models/Article.swift
> +//            _title.removeSubrange(range)
應該是，要確認可以去群組問。

2021-10-17 11:08 UTC, marcussfu commented on Ptt/API/Models/Article.swift
> +//            _title.removeSubrange(range)
已確認，只在測試環境有

2021-11-16 13:29 UTC, marcussfu commented on Ptt/Flows/BoardFlow/Controllers/BoardViewController.swift
> +        refresh()
corrected.

2021-11-22 22:51 UTC, marcussfu commented on Ptt/Flows/BoardFlow/BoardCoordinator.swift
> +        router.push(composeArticleView)
用denkeni的方法"把 ComposeArticleViewController 放進一個新的 UINavigationController，再 present 這個 nav "，已經可以顯示navigation bar了，離開ComposeArticleViewController改成dismiss

2021-11-23 12:08 UTC, denkeni commented on Ptt/Flows/ComposeArticleFlow/Controllers/ComposeArticleViewController.swift
> +        setConstraint()
I'll help do it later.

2021-11-23 12:09 UTC, denkeni approved these changes

2021-11-25 13:57 UTC, denkeni approved these changes

2021-11-27 01:44 UTC, merged